"""add global product inventory

Revision ID: 607db37d9668
Revises: 94c167c426cd
Create Date: 2026-09-08 20:31:33.444430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607db37d9668'
down_revision: Union[str, Sequence[str], None] = '94c167c426cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('physical_stock', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('physical_stock >= 0', name='physical_stock_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_unique_constraint('uq_pos_inventory_pos_product', 'pos_inventory', ['pos_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pos_inventory_pos_product', 'pos_inventory', type_='unique')
    op.drop_table('product_inventory')
    # ### end Alembic commands ###
